### ISSUE TITLE
Changing Readme.md file

### ISSUE THREAD

**Issue by Milimeter** [loonix/flutter-offline-chat#1]
How does one connect the devices together for the offline communication.
i connected to the has network via hotspot but was not  connecting.
could you perhaps try to update the readme file for implementation details

**Comment by loonix** [comment]
I still haven't fully tested this concept, but feel free to contribute to the project. It's still a work in progress

**Comment by loonix** [comment]
Hey, fixed it partially for you to have a look. Added some instructions on the readme file.

Hope it helps and feel free to contribute.
